name: mem_game
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0-219.0.dev

dependencies:
  flutter:
    sdk: flutter
  #database
  hive: ^2.0.0
  hive_flutter: ^1.1.0
  
  #state
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  provider: ^6.1.4
  build_runner: ^2.4.15

  #google
  google_mobile_ads: ^5.3.1
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  json_serializable: ^6.9.0
  lottie: ^3.3.1
  flutter_layout_grid: ^2.0.8
  #firebase
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.6

  #JSON
  json_annotation: ^4.7.0

  #Rest
  http: ^1.3.0
  dio: ^5.8.0+1

  very_good_analysis: ^7.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
 

flutter:
  uses-material-design: true

  assets:
    - assets/card_images/level1/
    - assets/card_images/level2/
    - assets/card_images/level3/
    - assets/lottie/